// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LibraryManagementSystem.Models
{
    public partial class Author
    {
        public Author()
        {
            ISBNs = new HashSet<Book>();
        }

        public string name { get; set; }
        public int Author_Id { get; set; }
        public string bio { get; set; }

        public virtual ICollection<Book> ISBNs { get; set; }
    }
}