// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LibraryManagementSystem.Models
{
    public partial class Book
    {
        public Book()
        {
            Authors = new HashSet<Author>();
            Categories = new HashSet<Category>();
            Orders = new HashSet<OrderTable>();
        }

        public int title { get; set; }
        public int ISBN { get; set; }
        public int Price { get; set; }
        public int image { get; set; }
        public int License_Quantity { get; set; }

        public virtual ICollection<Author> Authors { get; set; }
        public virtual ICollection<Category> Categories { get; set; }
        public virtual ICollection<OrderTable> Orders { get; set; }
    }
}